language:
  - node_js

node_js:
  - 4.1
  - 4.0

install:
  - npm install

script:
  - npm test

after_success:
  - npm run patch-release

deploy:
  provider: npm
  email: oliviercolonna@gmail.com
  api_key:
    secure: kEfNhy92Zx0eM6YV2C+UxYo06F5tn+Tpv/rPicV2E0Mb1feonthpZP3cWPpnDl59fCU3MSOMW3bgN0xUq8ZG+8IQbubMH7oXESLnZDXuE9Mht3ANvulldYcait0IaNAX1QK/v9UG/yfeOCJEuI/6zsKx7l9lD0kmN06PccnlCB4DEoPq8I//fpw4+gaEpqyiMcpL3R+6S5S6ak93mum+SFbtfbMLlIkaq0SlcTxrIHG9eSzSfuYTghiddkyIMi3AcWtD9CYJydDk0TbIRJ6/feqL6Lr5z8urCLGIH9HtehAkuYGDzTAE7OWNpZ/X/9+6sv9ADVfgPo6g6EGVJlkI/f3XtVLuPr93JXjR+JzeSOgizP3XkI7Farliom3FGZfrvtW7DNuI23o0L2yZ1whhnHhiZSWfWEcyqVwqc7YCBLkVM4Oz3cfHliakggivHExWPHbWkxzZ3d+KRGeOkKdshfx10nHGhfi+VU+9k/p6iyV3ChcaMa+BPp9nz1nI/u+BHI2FgcCm2TTkB5Gtv7kxiGRc/I9zXqIHWfuZo7ARD4MXgVpQgha+A44Oc5Y5bkW/OUtmXn8x9pSqK88tYwpOkKo9mipv8uyIz/rW2EcWc6qJ+Ay23FabPokt9s72zw1KEUY9puAswF8aW7Yj6qytUulvUWS0Li3PKYnSeTk//N0=
  on:
    tags: true
    all_branches: true